### ISSUE TITLE
[Bug] - esx_script - Using ox_inventory on the server will cause problems with ESX Multicharacter, players cannot enter the server

### ISSUE THREAD

**Issue by 2749773995** [esx-framework/esx_core#1079]
Describe the bug
Using ox_inventory on the server will cause problems with ESX Multicharacter, players cannot enter the server

Framework
ESX 1.9.4

Resource version
2.30.7

I am using Esx Legacy 1.9.4. When the server does not use ox_inventory, everything is normal, but when I enable ox_inventory, any player will not be able to enter when connecting to the server and a prompt will appear:
Connection rejected by gaogaolongjiang's server: [ESX Multicharacter] ESX Cannot Connect to your database. Please make sure it is correctly configured in your server.cfg

Screenshots
![~`{AROG{2{KX`SFA`%%`CX](https://github.com/esx-framework/esx_core/assets/104758168/2a12a821-65fa-455c-9151-48352eedca7c)

**Comment by thesysadmindev** [comment]
This is not a bug. The problem is that either you're not telling us the correct version or either ESX Multicharacter, Oxmysql or es_extended is an old version. Updating all three to the latest versions will resolve the issue.

Please do some research before posting issues that have been discussed time and time again.
