### ISSUE TITLE
[Feature Request] - esx_documentation - Add usage `ESX.RegisterPlayerFunctionOverrides(index, overrides)` and `ESX.SetPlayerFunctionOverride(index)`

### ISSUE THREAD

**Issue by Mesrine67** [esx-framework/esx_core#1332]
Is it possible to add these functions to the documentation? example it is of little use to create this type of code:

```lua
RegisterCommand('setWounding', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.setWounding('bonesOrBodyParts', {causeInfo = 'UPPER_BODY', state = 300, ...})
end, false)
RegisterCommand('getWounding', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    print(xPlayer.getWounding('RFOOT', 'UPPER_BODY'))
    print(json.encode(xPlayer.getWounding(),{indent=true}))
end, false)
```

**Comment by Gellipapa** [comment]
@Mesrine67 Hi! Yes, this will be included in the documentation in the future. Thanks for the indication.

**Comment by Mesrine67** [comment]
Wasn't this added to the documentation?

**Comment by Gellipapa** [comment]
Hi! @Mesrine67 You misunderstood the functionality of this, it's a very old development that was made to solve ox_inventory compatibility. 

If you read through the implementation itself you will see that in this case you can't add anything else. 

It only works if you don't use ox_inventory, but 98% of the servers use ox-inventory so they can never use this feature because then ox_inventory will not be compatible with es_extended. 

So we have closed this issu until this is thought through, but for now we are not dealing with core stuff like this anymore because it is a legacy project and we are trying to focus on new stuff.
