### ISSUE TITLE
[Bug] - es_extended - Issue

### ISSUE THREAD

**Issue by RoccoRP** [esx-framework/esx_core#1389]
i use version '1.10.7'

when i quit fivem and try to relog , i have this  error

![image](https://github.com/user-attachments/assets/14e47b5c-4588-4944-908e-287c7ae743d5)

i have to restart server to fix every time

**Comment by Gellipapa** [comment]
@RoccoRP Hi! You probably have a slow server and when you log off it still detects that you are logged in and will not allow multiple logins and since you restart the whole server you are definitely not logged in anymore so it will let you log in. 

There is a config setting to handle this but I don't recommend using it because it is a debug mode. 

You might also want to check the server console for any errors when you log out of the server. 

No one has reported this error yet, I use ESX daily and have not experienced this error so this must be a one off.
