### ISSUE TITLE
[Bug] - esx_script - Issue

### ISSUE THREAD

**Issue by justinsanjp** [esx-framework/esx_core#1395]
**Describe the bug**
/setjob does not work as it should, it gives errors, you get the job in the ui, but not in the database, e.g. doorlook thinks the player is not in this job. this is not a doorlook problem.

**To Reproduce**
just enter /setjob <id> <job> <rang>
example: /setjob 1 taxi 2
**Expected behavior**
that all is okay, an all is working as it should. but now it dosent work.

**Screenshots**
![Screenshot (30)](https://github.com/user-attachments/assets/fb0c363e-d55f-492f-a6c4-a489a547f387)

**Debug Info (please complete the following information):**
 - OS: ( Windows)
 - serveros: Linux
 -  FiveM Artifact:
fx: b9601
 - ESX Version:
 Core: latest from github
 rest i dont know i ussed the recipe a coupple weeks ago

**Additional context**
i want to set my job but it dosent work as  normaly.

**Comment by Gellipapa** [comment]
@justinsanjp Hi! I have not encountered a problem with the setjob, I checked where you are getting the error where one of your jobs is not set correctly. Most likely the label or name value is nil. 

Open your jobs and jobs_grade table and see if you have a value in each of your tables. 

The other thing is to see if you are using this command somewhere: ESX.CreateJob if you are, then see what data you are passing there. 

The problem is that the value is nil, so fix that and you should be fine. It's a data error it's not an ESX error.

**Comment by Gellipapa** [comment]
Hi! @justinsanjp I have tested es_extended on 1.10.7 with a fresh install and the setjob works without errors. 
It is recommended to do a clean install via txadmin.
Thanks.

**Comment by justinsanjp** [comment]
yeah, i re installed everytiing, it seems like my version of esx was buggy at this time
