### ISSUE TITLE
[Bug] - esx_script - Issue

### ISSUE THREAD

**Issue by jaimelpdev** [esx-framework/esx_core#1405]
hi everyone,
I have this problem, someone can help me?
![imagen_2024-09-28_121859903](https://github.com/user-attachments/assets/c1dd0538-f056-462b-a89c-3cf5ed757510)

**Comment by Gellipapa** [comment]
Hi! @jaimelpdev Run this SQL on your users table.

ALTER TABLE `users`ADD COLUMN `last_property` VARCHAR(255) NULL DEFAULT

**Comment by jaimelpdev** [comment]
I did it now and the error persist.

**Comment by Gellipapa** [comment]
@jaimelpdev Hi! It's okey, go to esx_property/server.lua find this row 
"ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `last_property` LONGTEXT NULL"
 and remove "IF NOT EXIST" part. 

Good query is: ALTER TABLE `users` ADD COLUMN `last_property` LONGTEXT NULL

After restart esx_property and it's works. I think you are use old mysql engine and your mysql version don't have "IF NOT EXISTS" logic. 

Solution update your sql or replace query.

**Comment by jaimelpdev** [comment]
Now the error dissapears, but when I was entry to the FiveM's server this error appears:
![image](https://github.com/user-attachments/assets/a886bb63-55d2-4f27-92dc-cea7dac99d69)

**Comment by Gellipapa** [comment]
@jaimelpdev Hi! It's okey, you should run this query on your SQL. (like phpmyadmin, or heidisql)
IMPORTANT first delete all users table. If you have any data, first of all export your database, after delete table and run this query, after you can import database and you get all latest data.

But all this shouldn't happen if you don't install ESX manually but through txadmin because then everything is done automatically and correctly by txadmin. Now specifically your database is probably broken in several places, I would suggest you reinstall it all via txadmin by entering the SQL data and txadmin will run the SQL queries.


```
CREATE TABLE IF NOT EXISTS `users` (
  `identifier` varchar(46) NOT NULL,
  `accounts` longtext DEFAULT NULL,
  `group` varchar(50) DEFAULT 'user',
  `inventory` longtext DEFAULT NULL,
  `job` varchar(20) DEFAULT 'unemployed',
  `job_grade` int(11) DEFAULT 0,
  `loadout` longtext DEFAULT NULL,
  `metadata` longtext DEFAULT NULL,
  `position` longtext DEFAULT NULL,
  `firstname` varchar(16) DEFAULT NULL,
  `lastname` varchar(16) DEFAULT NULL,
  `dateofbirth` varchar(10) DEFAULT NULL,
  `sex` varchar(1) DEFAULT NULL,
  `height` int(11) DEFAULT NULL,
  `skin` longtext DEFAULT NULL,
  `status` longtext DEFAULT NULL,
  `is_dead` tinyint(1) DEFAULT 0,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `disabled` tinyint(1) DEFAULT 0,
  `last_property` varchar(255) DEFAULT NULL,
  `last_property2` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `last_seen` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `phone_number` varchar(20) DEFAULT NULL,
  `pincode` int(11) DEFAULT NULL,
  `last_property10` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`identifier`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;
```
